### 이슈 등록
POST {{host}}/api/issues
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhdXRoIiwiaXNzIjoiamFyYSIsImV4cCI6MTY2ODQzMjM4NywiaWF0IjoxNjY4NDI4Nzg3LCJ1c2VySWQiOjEsImVtYWlsIjoiZGV2QGdtYWlsLmNvbSIsInVzZXJuYW1lIjoi7ZmN6ri464-ZIn0.bd4EAtZsceCI_ItGyQSA_QkhWQ3Zg7f5jftbU23KNDk

{
  "summary" : "테스트",
  "description" : "설명",
  "type" : "TASK",
  "priority" : "LOW",
  "status" : "TODO"
}

### 이슈 조회
GET {{host}}/api/issues?status=TODO
Accept: application/json

### 이슈 상세 조회
GET {{host}}/api/issues/{{issueId}}
Accept: application/json

### 이슈 수정
PUT {{host}}/api/issues/{{issueId}}
Content-Type: application/json

{
  "summary" : "변경제목",
  "description" : "바뀐 설명",
  "type" : "BUG",
  "priority" : "HIGH",
  "status" : "TODO"
}

### 이슈 삭제
DELETE {{host}}/api/issues/{{issueId}}/comments/{{commentId}}